sudo: true
dist: xenial
services:
  - mysql
language: node_js
node_js:
  - "8"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mfcapi_test;'
install:
  - npm install
before_script:
  - node_modules/.bin/sequelize db:migrate:undo:all
  - node_modules/.bin/sequelize db:migrate
notifications:
  email:
    on_success: never
    on_failure: always