sudo: true
dist: xenial
services:
  - mysql
language: node_js
node_js:
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mfcapi;'
install:
  - npm install
notifications:
  email:
    on_success: never
    on_failure: always