sudo: true
dist: xenial
services:
  - mysql
language: node_js
node_js:
  - "8"
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('abc#123') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p abc#123
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mfcapi_test;'
install:
  - npm install
before_script:
  - node_modules/.bin/sequelize db:migrate:undo:all
  - node_modules/.bin/sequelize db:migrate
notifications:
  email:
    on_success: never
    on_failure: always